title = "じつかいせきのTRPG雑記"

theme = "hugo-theme-docport"

baseURL = "https://minori-akizuki.github.io/trpg_notes/"
publishDir = "docs"
canonifyurls = true

languageCode = "en-us"
DefaultContentLanguage = "en"
pygmentsCodeFences = true
pygmentsStyle = "monokai"

defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false

# googleanalytics = "UA-123-45"

disableKinds = ["taxonomy", "taxonomyTerm", "category", "RSS"]

# Keep this as is
[outputs]
home = [ "HTML", "RSS", "JSON"]

# Site params
[params]
ordersectionsby = "weight" # ordersectionsby = "title"
color_main = "#739973"
color_second = "#b30000"
disableSearch = false # default is false
disableNavChevron = false # set true to hide next/prev chevron, default is false
menushortcutsnewtab = false # set true to open shortcuts links to a new tab/window

#editURL = "https://github.com/vjeantet/hugo-theme-docport/edit/master/exampleSite/content/"
enableGitInfo = true



[mediaTypes]
  [mediaTypes."application/netlifyconfig"]
    suffixes = ["yml"]

[outputFormats]
[outputFormats.netlifyyaml]
mediaType = "application/netlifyconfig"
isPlainText = true
isHTML = false
notAlternative = true

[markup.goldmark.renderer]
unsafe = true

# Code highlight configuration
[markup.highlight]
codeFences = true
guessSyntax = true
hl_Lines = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = "monokai"
tabWidth = 2

#
# top menu shotcuts
#
[[menu.shortcuts]]
name = "Github"
identifier = "ds"
url = "https://github.com/Minori-Akizuki/trpg_notes"
weight = 10

[[menu.shortcuts]]
name = "Twitter"
url = "https://twitter.com/real_analysis"
weight = 10
